# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao', models.TextField(blank=True, null=True)),
                ('visao', models.TextField(blank=True, null=True)),
                ('valores', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sobre Nós',
                'verbose_name_plural': 'Sobre Nós',
            },
        ),
    ]
