# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_nos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrenos',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Entrada'),
            preserve_default=False,
        ),
    ]
