# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Atalho')),
                ('descricao', models.TextField(null=True, verbose_name='descricao')),
                ('icone', models.ImageField(upload_to='projetos')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'verbose_name': 'Projeto',
            },
        ),
    ]
